alias c='clear'
alias ls='ls -aF --color'
alias ..='cd ../'
alias nsess='tmux new -s'
alias asess='tmux attach -t'
alias ksess='tmux kill-session -t'
alias lsess='tmux list-sessions'
alias csess='tmux switch -t'
# alias nwind='tmux new-window'
# alias swind='tmux select-window -t :'
# alias rwind='tmux rename-window'
alias isess='tmux info'
alias x='exit'
alias ll='ls -al --color'
alias n='nnn'
alias rm='rm -iv'
alias wget='wget -c'
alias grep='grep --color=auto'

EDITOR=vim
